image: gitlab/dind


stages:
#  - test
  - build
  - production


before_script:
  - curl -fsSL https://get.docker.com/
  - groupadd docker
  - usermod -aG docker root

#testcases:
#    stage: test
#    script:
#      - /root/.pyenv/versions/app/bin/pip install -r /srv/app/requirements/requirements.txt
#      - python manage.py test --noinput

job_build:
    image: jhe702/basebuild:base
    stage: build

    script:
        - docker login -u joohyon.lee@octocolumn -p bisu103702 registry.gitlab.com
        - docker build -t registry.gitlab.com/joohyon.lee/devocto .
        - docker push registry.gitlab.com/joohyon.lee/devocto

    only:
    - master


job_production:
    stage: production
    script:
        - docker login registry.gitlab.com
        - docker pull registry.gitlab.com/joohyon.lee/devocto
        - docker stop octocolumn || true && docker rm octocolumn || true
        - docker run --name=octocolumn -p 80:80 443:443 -itd registry.gitlab.com/joohyon.lee/devocto
    only:
    - master